In [1]:
# (NumPy)

import numpy as np

arr = [['Ane','Abi','Adi'],['Belgium','Belgium','France'],['Brussels','Brussels','Paris']]

np.array(arr)

array([['Ane', 'Abi', 'Adi'],
       ['Belgium', 'Belgium', 'France'],
       ['Brussels', 'Brussels', 'Paris']], dtype='<U8')

In [2]:
# built in Python range for NumPy

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.linspace(2,.25,3)

array([2.   , 1.125, 0.25 ])

In [5]:
# CREATE IDENDTITY MATRIX

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# GENERATE RANDOM NUMBERS

# 1D Array
np.random.rand(2)

# 2D Array
np.random.rand(3,3) # unlike the other methods where we pass it on as tuple instead we pass it with comma 

array([[0.95245941, 0.94825178, 0.21517668],
       [0.21017474, 0.12356784, 0.20149443],
       [0.2766662 , 0.71192073, 0.6226115 ]])

In [7]:
# gaussian and normal distribution 
np.random.randn(3,3)

array([[-0.5979326 ,  0.15237058,  1.20361733],
       [-1.92328607, -1.34501332, -0.19646409],
       [-0.03816831,  0.87248307, -0.20311504]])

In [8]:
 a= np.random.randint(50,1000,9)
 a.argmax()

5

In [9]:
arr = np.arange(15)
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
ane = np.random.randint(1,50,10)

if 10 in ane:
    print("The max value is : ",ane.max())
else:
    print("Better Luck Next Time :-(")

Better Luck Next Time :-(


In [11]:
ane

array([21, 15,  1,  4, 36,  1, 17, 30, 29, 24])

In [12]:
print(ane.max())
ane.argmax()

36


4

In [13]:
a2 = int(input('Enter the number: '))
ane = np.random.randint(1,50,10)

for a2 in range(1):
    if a2 in ane:
        print("The max value is : ",ane.max())
    elif a2 in ane:
        print('The min value is : ',ane.min())
    else:
        print("Better Luck Next Time :-(")
    print("Position of the maximum value is: ",ane.argmax())
    print('Position of minimum value is: ',ane.argmin())

Better Luck Next Time :-(
Position of the maximum value is:  8
Position of minimum value is:  0


In [14]:
a2 = ane.reshape(2,5)

In [15]:
a2.shape

(2, 5)

In [16]:
a2.dtype

dtype('int64')

In [17]:
a2

array([[ 1, 27, 31, 27, 35],
       [16, 30, 10, 48, 21]])

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
arr[8]

8

In [20]:
arr[10:]

array([10, 11, 12, 13, 14])

In [21]:
slice_arr = arr[0:5]

In [22]:
slice_arr

array([0, 1, 2, 3, 4])

In [23]:
slice_arr[:] = int(input())

In [24]:
slice_arr

array([23, 23, 23, 23, 23])

In [25]:
arr

array([23, 23, 23, 23, 23,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr = np.arange(15)

In [27]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

In [28]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [29]:
arr_2d[3][2]

12

In [30]:
arry_name = np.array([1,2,3])

In [31]:
arry_name

array([1, 2, 3])

In [32]:
arr_2d[1:4,:2]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [33]:
bool_arr = arr > 5

In [34]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
arr1 = np.arange(20).reshape(5,4) #another method to create a 2d matrix

In [36]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [37]:
arr1[:,3:4]

array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])

In [38]:
##################### Operations #######################

In [39]:
add1 = np.arange(10)

In [40]:
add1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
add1 * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [42]:
add1 / add1

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [43]:
1 / add1

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [44]:
np.sinh(add1)

array([0.00000000e+00, 1.17520119e+00, 3.62686041e+00, 1.00178749e+01,
       2.72899172e+01, 7.42032106e+01, 2.01713157e+02, 5.48316123e+02,
       1.49047883e+03, 4.05154190e+03])

In [49]:
np.log(add1)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [54]:
np.conj(ane)

array([ 1, 27, 31, 27, 35, 16, 30, 10, 48, 21])

In [55]:
##############################Exe#######################

In [59]:
# create array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
# create array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
# create array of 10 fives
np.ones(10)*5
# or we can do it as np.ones(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [62]:
# array of integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [65]:
# even numbers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [66]:
# 3x3 matrix from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
arry_name = np.array([[1,2,3],[4,5,6],[7,8,9]])
arry_name

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
# random number for gausian and std deviation
np.random.randn(25)

array([-2.06652542e-01, -6.30991390e-02, -6.33722732e-01,  1.37109815e+00,
       -1.40930364e-01,  5.81721370e-01, -3.84137568e-01, -7.53437334e-01,
        8.66464338e-01, -9.09324279e-02, -7.29959594e-01,  4.74216271e-01,
        4.04446711e-01, -1.95828331e-01,  1.44331079e-03,  2.06313668e+00,
       -2.79901642e-01, -1.81724742e-01, -2.16204938e+00,  1.07034249e+00,
       -1.26082553e+00, -8.83425410e-01,  1.51135597e-01,  3.04591290e-01,
       -3.19106363e-01])

In [73]:
# 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# random number btwn 0 and 1
np.random.rand(1)

array([0.89065627])

In [10]:
np.random.rand(25).reshape(5,5)

array([[0.07979665, 0.78929579, 0.28313918, 0.90631668, 0.17026705],
       [0.33532868, 0.30450331, 0.18673787, 0.59254767, 0.07719621],
       [0.79345075, 0.16316816, 0.85005133, 0.02083682, 0.4343564 ],
       [0.29826049, 0.27847632, 0.97525091, 0.94213545, 0.60465779],
       [0.83446973, 0.22788184, 0.80837372, 0.14929758, 0.40057828]])

In [67]:
np.linspace(0.01,1,100).reshape(10,10)
# or we can tery like np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [18]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [19]:
# Slicing and Indexing
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [24]:
mat[3,4]

20

In [36]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [37]:
mat[4]

array([21, 22, 23, 24, 25])

In [39]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
np.sum(mat)

325

In [47]:
np.std(mat)

7.211102550927978

In [59]:
column_sums = mat.sum(axis=0)
column_sums

array([55, 60, 65, 70, 75])

In [60]:
mat.sum(axis=1) # sum of rows

array([ 15,  40,  65,  90, 115])

In [1]:
pip list

Package                            Version
---------------------------------- -------------------
absl-py                            0.9.0
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
applaunchservices                  0.2.1
appnope                            0.1.0
appscript                          1.0.1
argh                               0.26.2
asgiref                            3.2.10
asn1crypto                         1.3.0
astroid                            2.3.3
astropy                            4.0
astunparse                         1.6.3
atomicwrites                       1.3.0
attrs                              19.3.0
autopep8                           1.4.4
Babel                              2.8.0
backcall                           0.1.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0